# https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
kind: Deployment
metadata:
  name: snykcon-2020-deployment # name of my deployment
spec:
  selector:
    matchLabels:
      app: snykcon-2020
  replicas: 2 # run two containers
  template:
    metadata:
      labels:
        app: snykcon-2020
    spec:
      containers:
        - name: snykcon-2020
          image: benlaplanche/snykcon-2020:latest # Docker Hub reference
          ports:
            - containerPort: 8080 # port to run our container on